"""empty message

Revision ID: 3c383133008b
Revises: c5745e845b25
Create Date: 2019-04-15 14:21:03.635349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c383133008b'
down_revision = 'c5745e845b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True, comment='vip名称'),
    sa.Column('grade', sa.String(length=10), nullable=True, comment='等级'),
    sa.Column('introduce', sa.TEXT(), nullable=True, comment='vip描述'),
    sa.Column('price', sa.String(length=10), nullable=True, comment='vip价格'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vip_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=200), nullable=True, comment='用户openid'),
    sa.Column('unionid', sa.String(length=200), nullable=True, comment='unionid'),
    sa.Column('buy_date', sa.DateTime(), nullable=True, comment='购买时间'),
    sa.Column('lose_date', sa.DateTime(), nullable=True, comment='购买时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('enter_date', sa.DateTime(), nullable=True, comment='录入时间'))
    op.drop_column('article', 'enter_data')
    op.add_column('user', sa.Column('add_date', sa.DateTime(), nullable=True, comment='用户入库时间'))
    op.add_column('user', sa.Column('age', sa.String(length=3), nullable=True, comment='年龄'))
    op.add_column('user', sa.Column('area', sa.String(length=100), nullable=True, comment='区域'))
    op.add_column('user', sa.Column('grade_vip', sa.String(length=10), nullable=True, comment='vip等级'))
    op.add_column('user', sa.Column('income', sa.String(length=10), nullable=True, comment='收入'))
    op.add_column('user', sa.Column('other_name', sa.String(length=100), nullable=True, comment='用户昵称'))
    op.add_column('user', sa.Column('sex', sa.String(length=5), nullable=True, comment='性别'))
    op.add_column('user', sa.Column('telnum', sa.String(length=11), nullable=True, comment='电话号码'))
    op.add_column('user', sa.Column('typephone', sa.String(length=50), nullable=True, comment='手机型号'))
    op.add_column('user', sa.Column('unionid', sa.String(length=200), nullable=True, comment='unionid'))
    op.add_column('user', sa.Column('want_buy', sa.String(length=50), nullable=True, comment='购买意向'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'want_buy')
    op.drop_column('user', 'unionid')
    op.drop_column('user', 'typephone')
    op.drop_column('user', 'telnum')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'other_name')
    op.drop_column('user', 'income')
    op.drop_column('user', 'grade_vip')
    op.drop_column('user', 'area')
    op.drop_column('user', 'age')
    op.drop_column('user', 'add_date')
    op.add_column('article', sa.Column('enter_data', mysql.DATETIME(), nullable=True, comment='录入时间'))
    op.drop_column('article', 'enter_date')
    op.drop_table('vip_order')
    op.drop_table('vip')
    # ### end Alembic commands ###
