"""empty message

Revision ID: 9fd8a0550113
Revises: 207a9346e8d3
Create Date: 2019-04-18 14:01:17.378126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fd8a0550113'
down_revision = '207a9346e8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vip_order', sa.Column('grade', sa.String(length=10), nullable=True, comment='等级'))
    op.alter_column('vip_order', 'lose_date',
               existing_type=mysql.DATETIME(),
               comment='到期时间',
               existing_comment='购买时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vip_order', 'lose_date',
               existing_type=mysql.DATETIME(),
               comment='购买时间',
               existing_comment='到期时间',
               existing_nullable=True)
    op.drop_column('vip_order', 'grade')
    # ### end Alembic commands ###
