"""empty message

Revision ID: c5745e845b25
Revises: d68405a69473
Create Date: 2019-04-15 13:54:02.288943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5745e845b25'
down_revision = 'd68405a69473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.TEXT(), nullable=True, comment='文章内容'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content')
    # ### end Alembic commands ###
