"""empty message

Revision ID: d45c515f96e4
Revises: 
Create Date: 2019-04-10 16:33:52.802375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45c515f96e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=50), nullable=True, comment='节id'),
    sa.Column('is_update', sa.String(length=5), nullable=True, comment='是否更新中'),
    sa.Column('article_title', sa.String(length=100), nullable=True, comment='标题'),
    sa.Column('article_price', sa.String(length=10), nullable=True, comment='节价格'),
    sa.Column('is_pay', sa.String(length=5), nullable=True, comment='是否付费'),
    sa.Column('is_trials', sa.String(length=5), nullable=True, comment='是否为试读'),
    sa.Column('pic_url', sa.String(length=200), nullable=True, comment='图片地址'),
    sa.Column('chapter_id', sa.String(length=50), nullable=True, comment='章id'),
    sa.Column('ebook_id', sa.String(length=50), nullable=True, comment='电子书id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(length=50), nullable=True, comment='章id'),
    sa.Column('chapter_title', sa.String(length=100), nullable=True, comment='章标题'),
    sa.Column('chapter_price', sa.String(length=10), nullable=True, comment='章价格'),
    sa.Column('is_pay', sa.String(length=5), nullable=True, comment='是否付费'),
    sa.Column('is_trials', sa.String(length=5), nullable=True, comment='是否为试读'),
    sa.Column('ebook_id', sa.String(length=50), nullable=True, comment='电子书id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebook_id', sa.String(length=50), nullable=True, comment='电子书id'),
    sa.Column('classification', sa.String(length=200), nullable=True, comment='所属分类'),
    sa.Column('ebook_title', sa.String(length=100), nullable=True, comment='电子书标题'),
    sa.Column('introduce', sa.String(length=500), nullable=True, comment='简介'),
    sa.Column('envelope_url', sa.String(length=255), nullable=True, comment='封皮地址'),
    sa.Column('ebook_price', sa.String(length=10), nullable=True, comment='价格'),
    sa.Column('total_chapter', sa.String(length=10), nullable=True, comment='总章数'),
    sa.Column('is_pay', sa.String(length=5), nullable=True, comment='是否付费'),
    sa.Column('free_trials', sa.String(length=10), nullable=True, comment='免费试读章节数'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebook_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebook')
    op.drop_table('chapter')
    op.drop_table('article')
    # ### end Alembic commands ###
