"""empty message

Revision ID: d68405a69473
Revises: 
Create Date: 2019-04-15 11:17:39.725665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68405a69473'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(length=20), nullable=True, comment='章序号'),
    sa.Column('ebook_id', sa.String(length=20), nullable=True, comment='电子书序号'),
    sa.Column('is_update', sa.String(length=5), nullable=True, comment='是否更新中'),
    sa.Column('article_title', sa.String(length=100), nullable=True, comment='标题'),
    sa.Column('article_price', sa.String(length=10), nullable=True, comment='节价格'),
    sa.Column('is_pay', sa.String(length=5), nullable=True, comment='是否付费'),
    sa.Column('is_trials', sa.String(length=5), nullable=True, comment='是否为试读'),
    sa.Column('pic_url', sa.String(length=200), nullable=True, comment='图片地址'),
    sa.Column('enter_data', sa.DateTime(), nullable=True, comment='录入时间'),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('ebook_id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(length=20), nullable=True, comment='章序号'),
    sa.Column('ebook_id', sa.String(length=20), nullable=True, comment='电子书序号'),
    sa.Column('chapter_title', sa.String(length=100), nullable=True, comment='章标题'),
    sa.Column('chapter_price', sa.String(length=10), nullable=True, comment='章价格'),
    sa.Column('is_pay', sa.String(length=5), nullable=True, comment='是否付费'),
    sa.Column('is_trials', sa.String(length=5), nullable=True, comment='是否为试读'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebook_id')
    )
    op.create_table('ebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebook_id', sa.String(length=20), nullable=True, comment='电子书序号'),
    sa.Column('classification', sa.String(length=200), nullable=True, comment='所属分类'),
    sa.Column('ebook_title', sa.String(length=100), nullable=True, comment='电子书标题'),
    sa.Column('introduce', sa.String(length=500), nullable=True, comment='简介'),
    sa.Column('envelope_url', sa.String(length=255), nullable=True, comment='封皮地址'),
    sa.Column('ebook_price', sa.String(length=10), nullable=True, comment='价格'),
    sa.Column('total_chapter', sa.String(length=10), nullable=True, comment='总章数'),
    sa.Column('is_pay', sa.String(length=5), nullable=True, comment='是否付费'),
    sa.Column('free_trials', sa.String(length=10), nullable=True, comment='免费试读章节数'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebook_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=200), nullable=True, comment='用户openid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_buys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=200), nullable=True, comment='用户openid'),
    sa.Column('ebook_id', sa.Integer(), nullable=True, comment='电子书序号'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_buys')
    op.drop_table('user')
    op.drop_table('ebook')
    op.drop_table('chapter')
    op.drop_table('article')
    op.drop_table('admin_login')
    # ### end Alembic commands ###
